networks:
  network-php:
    name: network-php
    external: true

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/app
    networks:
      - network-php
    depends_on:
      - php

  php:
    container_name: php
    build: ./images/php
    volumes:
      - ./www:/app
    working_dir: /app
    networks:
      - network-php
