networks:
  network2:
    name: network2

services:
  nginx2:
    container_name: nginx2
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - network2
    depends_on:
      - php2
  php2:
    container_name: php2
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
    networks:
      - network2
